### ISSUE TITLE
linking -lmath

### ISSUE THREAD

**Issue by cogmeta** [cpuimage/AudioDenoise#1]
I am getting following errors probably because -lmath is not linked. how can i fix it?

[ 20%] Linking C executable denoise
CMakeFiles/denoise.dir/stftDenoise.c.o: In function `make_hanning_window':
stftDenoise.c:(.text+0x14c): undefined reference to `cosf'
CMakeFiles/denoise.dir/stftDenoise.c.o: In function `stftDenoise_adaptive_block':
stftDenoise.c:(.text+0x1008): undefined reference to `sqrtf'
CMakeFiles/denoise.dir/kiss_fft.c.o: In function `kf_factor':
kiss_fft.c:(.text+0x1574): undefined reference to `sqrt'
kiss_fft.c:(.text+0x1580): undefined reference to `floor'
CMakeFiles/denoise.dir/kiss_fft.c.o: In function `kiss_fft_alloc':
kiss_fft.c:(.text+0x1788): undefined reference to `cos'
kiss_fft.c:(.text+0x17b0): undefined reference to `sin'
CMakeFiles/denoise.dir/kiss_fftr.c.o: In function `kiss_fftr_alloc':
kiss_fftr.c:(.text+0x1cc): undefined reference to `cos'
kiss_fftr.c:(.text+0x1f4): undefined reference to `sin'
collect2: error: ld returned 1 exit status
CMakeFiles/denoise.dir/build.make:172: recipe for target 'denoise' failed
make[2]: *** [denoise] Error 1
CMakeFiles/Makefile2:67: recipe for target 'CMakeFiles/denoise.dir/all' failed
make[1]: *** [CMakeFiles/denoise.dir/all] Error 2
Makefile:83: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by cpuimage** [comment]
@cogmeta 
in CMakeLists.txt add a line "target_link_libraries(denoise -lm)"

**Comment by cogmeta** [comment]
Thanks. That fixed it. Can you elaborate on the licence? can you please add the LICENCE file if it Apache 2.0 or MIT? Thanks.

**Comment by cpuimage** [comment]
@cogmeta  the MIT LICENCE  file has been added, now.

**Comment by cogmeta** [comment]
Thanks.
