### ISSUE TITLE
大神好，我对比了一下你的输出和官网的代码发现了问题

### ISSUE THREAD

**Issue by Leobewin** [cpuimage/AudioDenoise#2]
我发现最后那段你的语音输出有噪声，但是matlab的官网代码没有噪声，能不能麻烦你解释一下，纯学习心态，麻烦了

**Comment by cpuimage** [comment]
@Leobewin 这个算法的思路是有问题，所以我已经放弃了这个算法。如果有问题还是需要你自行排查。

**Comment by cpuimage** [comment]
@Leobewin 这个问题是样本数没有达到目标数量，请自行处理，由于这个算法存在几个方面的缺陷，所以没有优化计划。
